
frontend_residence:
    path: /residence
    controller: App\Controller\Frontend\Residence\ResidenceController::index
    methods: [GET]


frontend_forum:
    path: /forum
    controller: App\Controller\Frontend\Forum\ForumController::index
    methods: [GET]


frontend_syndicat:
    path: /syndicat
    controller: App\Controller\Frontend\Syndicat\SyndicatController::index
    methods: [GET]


frontend_evenement:
    path: /evenement
    controller: App\Controller\Frontend\Evenement\EvenementController::index
    methods: [GET]
