frontend_settings:
    path: /settings
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'frontend/settings/settings.html.twig'
