param(
    [Parameter(Mandatory = $true)]
    [string] $PhpExe,

    [Parameter(Mandatory = $true)]
    [string] $ProjectDir,

    [Parameter(Mandatory = $true)]
    [string] $Extensions
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $PhpExe)) {
    Write-Host "[ERROR] PHP executable not found: $PhpExe"
    exit 1
}

if (-not (Test-Path -LiteralPath $ProjectDir)) {
    Write-Host "[ERROR] Project directory not found: $ProjectDir"
    exit 1
}

$phpDir = Split-Path -Parent $PhpExe
$extDir = Join-Path $phpDir 'ext'
$projectIni = Join-Path $ProjectDir 'php.ini'
$extensionList = $Extensions -split '[,\s]+' | Where-Object {
    -not [string]::IsNullOrWhiteSpace($_) -and $_ -ne 'openssl'
}

$lines = @(
    '; Generated by Syndicati setup for Symfony CLI local server.',
    '; Do not commit real machine-specific paths.',
    ('extension_dir="' + $extDir.Replace('\', '/') + '"'),
    'date.timezone=UTC'
)

foreach ($extension in $extensionList) {
    $lines += "extension=$extension"
}

Set-Content -LiteralPath $projectIni -Value ($lines -join [Environment]::NewLine) -Encoding ASCII
Write-Host "[OK] Wrote Symfony project php.ini: $projectIni"
Write-Host "[INFO] extension_dir=$extDir"
exit 0
